<a href="https://colab.research.google.com/github/MhilmiT/DAA/blob/main/DAA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
aList = ["JOHN",33, "Toronto", True]
print(aList)

['JOHN', 33, 'Toronto', True]


In [ ]:
hList = ["Tileng", 212, 3.13, False]
print(hList)

['Tileng', 212, 3.13, False]


In [ ]:
mahasiswa = ["Muhammad Hilmi", 2021071030, "Informatiks", "DDA", "14/09/2022", "Univeritas  Pembangunan Jaya"]
print(bList)

['Muhammad Hilmi', 2021071030, 'Informatiks', 'DDA', '14/09/2022', 'Univeritas  Pembangunan Jaya']


In [ ]:
bin_colors = ['red', 'green', 'blue', 'yellow']
bin_colors[1]

'green'

In [ ]:
bin_colors = ['red', 'green', 'blue', 'yellow']
bin_colors[1:3]

['green', 'blue']

In [ ]:
mahasiswa = ["Muhammad Hilmi", 2021071030, "Informatiks", "DDA", "14/09/2022", "Universitas  Pembangunan Jaya"]
mahasiswa[5]



'Universitas  Pembangunan Jaya'

In [ ]:
mahasiswa = ["Muhammad Hilmi", 2021071030, "Informatiks", "DDA", "14/09/2022", "Universitas Pembangunan Jaya"]
mahasiswa[1:3]

['2021071030', 'Informatiks']

In [ ]:
bin_colors = ['red', 'green', 'blue', 'yellow']
for aColor in bin_colors:
  print(aColor + " Square")

red Square
green Square
blue Square
yellow Square


In [ ]:
for abc in mahasiswa:
  print("UPJ ", abc)

UPJ  Muhammad Hilmi
UPJ  2021071030
UPJ  Informatiks
UPJ  DDA
UPJ  14/09/2022
UPJ  Universitas  Pembangunan Jaya


In [ ]:
warna = ('Red', 'green', 'blue', 'yellow')
warna[0]

'Red'

In [ ]:
warna[2:]

('blue', 'yellow')

In [ ]:
UPJ = ('Universitas','Pembangunan', 'Jaya')
UPJ[0:]


('Universitas', 'Pembangunan', 'Jaya')

In [ ]:
nested_tuple = (100,(200,400,600),(300),(400,800))
print(nested_tuple)





(100, (200, 400, 600), 300, (400, 800))


In [ ]:
warna = {"Manual_color" : "Yellow", "approved_color" : "Green", "refused_color" : "Red"}
print(warna)

'Yellow'

In [ ]:
warna['aprovved_color']="Purple"
print(warna)

{'Manual_color': 'Yellow', 'aprovved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
mahasiswa = {
    "Nama" : "Muhammad Hilmi", 
    "Nim" : "2021071030", 
    "Prodi" : "Informatika", 
    "Universitas" : "UPJ"}
print(mahasiswa)

{'Nama': 'Muhammad Hilmi', 'Nim': '2021071030', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
green = {'Grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'Grass'}


In [ ]:
yellow={'dandelions', 'fire hydrant', 'leaves'}
red   ={'blood', 'rose','fire hydrant', 'leaves'}
print(yellow|red)
print(yellow&red)
print(type(yellow))

{'blood', 'dandelions', 'rose', 'fire hydrant', 'leaves'}
{'fire hydrant', 'leaves'}
<class 'set'>


In [ ]:
import pandas as pd
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])
    


In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df


id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
import pandas as pd
df = pd.DataFrame([
['1', 'Informatika', 50, 30, 20],
['2', 'Sistem Informasi',55, 30,25],
['3', 'Teknik SIpil', 40, 30, 10]])

    

In [ ]:
df.columns = ['No', 'Prodi', 'Mahasiwa', 'Laki-laki', 'Perempuan']
df

No             Prodi  Mahasiwa  Laki-laki  Perempuan
0  1       Informatika        50         30         20
1  2  Sistem Informasi        55         30         25
2  3      Teknik SIpil        40         30         10

In [ ]:
import numpy as np 
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)  
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
Matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(Matrix)



[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [ ]:
print(Matrix.transpose())

[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [ ]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [ ]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [ ]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [ ]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
